In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [4]:
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred + 1e-7) + (1 - y_true) * np.log(1 - y_pred + 1e-7))

In [5]:
def train_neural_network(X, y, epochs=10000, lr=0.1):
    input_dim = X.shape[1]
    weights = np.random.uniform(size=(input_dim, 1))
    bias = np.random.uniform(size=(1,))

    for epoch in range(epochs):
        linear_output = np.dot(X, weights) + bias
        predictions = sigmoid(linear_output)

        loss = binary_cross_entropy(y, predictions)

        error = predictions - y
        d_pred = error * sigmoid_derivative(predictions)

        weights -= lr * np.dot(X.T, d_pred)
        bias -= lr * np.sum(d_pred)

        if epoch % 1000 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
    
    return weights, bias

In [6]:
def predict(X, weights, bias):
    return sigmoid(np.dot(X, weights) + bias) >= 0.5

In [7]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

logic_gates = {
    "AND": np.array([[0], [0], [0], [1]]),
    "OR": np.array([[0], [1], [1], [1]]),
    "NAND": np.array([[1], [1], [1], [0]]),
    "NOR": np.array([[1], [0], [0], [0]]),
    "XOR": np.array([[0], [1], [1], [0]])
}

for gate_name, y in logic_gates.items():
    print(f"\nTraining for {gate_name} gate:")
    weights, bias = train_neural_network(X, y, epochs=10000, lr=0.1)
    predictions = predict(X, weights, bias).astype(int)
    print(f"Predictions for {gate_name} gate:\n{predictions.reshape(-1)}")


Training for AND gate:
Epoch 0, Loss: 0.8058
Epoch 1000, Loss: 0.1752
Epoch 2000, Loss: 0.1174
Epoch 3000, Loss: 0.0923
Epoch 4000, Loss: 0.0778
Epoch 5000, Loss: 0.0683
Epoch 6000, Loss: 0.0614
Epoch 7000, Loss: 0.0561
Epoch 8000, Loss: 0.0520
Epoch 9000, Loss: 0.0486
Predictions for AND gate:
[0 0 0 1]

Training for OR gate:
Epoch 0, Loss: 0.4648
Epoch 1000, Loss: 0.1254
Epoch 2000, Loss: 0.0815
Epoch 3000, Loss: 0.0636
Epoch 4000, Loss: 0.0536
Epoch 5000, Loss: 0.0470
Epoch 6000, Loss: 0.0423
Epoch 7000, Loss: 0.0387
Epoch 8000, Loss: 0.0359
Epoch 9000, Loss: 0.0336
Predictions for OR gate:
[0 1 1 1]

Training for NAND gate:
Epoch 0, Loss: 0.7677
Epoch 1000, Loss: 0.1848
Epoch 2000, Loss: 0.1208
Epoch 3000, Loss: 0.0940
Epoch 4000, Loss: 0.0789
Epoch 5000, Loss: 0.0690
Epoch 6000, Loss: 0.0619
Epoch 7000, Loss: 0.0566
Epoch 8000, Loss: 0.0523
Epoch 9000, Loss: 0.0489
Predictions for NAND gate:
[1 1 1 0]

Training for NOR gate:
Epoch 0, Loss: 1.2981
Epoch 1000, Loss: 0.1265
Epoch 20